//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LocalizedText", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to og.
        /// </summary>
        internal static string AndX {
            get {
                return ResourceManager.GetString("AndX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skal.
        /// </summary>
        internal static string AttendingButton {
            get {
                return ResourceManager.GetString("AttendingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rom.
        /// </summary>
        internal static string AvailibleRoomOverviewRoomLabel {
            get {
                return ResourceManager.GetString("AvailibleRoomOverviewRoomLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ledige rom i dag på Galleriet.
        /// </summary>
        internal static string AvailibleRoomsWindowName {
            get {
                return ResourceManager.GetString("AvailibleRoomsWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to innsjekket.
        /// </summary>
        internal static string CheckedInToOngoing {
            get {
                return ResourceManager.GetString("CheckedInToOngoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to innsjekk.
        /// </summary>
        internal static string CheckInButton {
            get {
                return ResourceManager.GetString("CheckInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommentar.
        /// </summary>
        internal static string EventInfoCommentLabel {
            get {
                return ResourceManager.GetString("EventInfoCommentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rom.
        /// </summary>
        internal static string EventInfoRoomLabel {
            get {
                return ResourceManager.GetString("EventInfoRoomLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lærer.
        /// </summary>
        internal static string EventInfoTeacherLabel {
            get {
                return ResourceManager.GetString("EventInfoTeacherLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tid.
        /// </summary>
        internal static string EventInfoTimeLabel {
            get {
                return ResourceManager.GetString("EventInfoTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uke.
        /// </summary>
        internal static string EventInfoWeekLabel {
            get {
                return ResourceManager.GetString("EventInfoWeekLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Én hendelse funnet.
        /// </summary>
        internal static string Filter1EventFoundLabel {
            get {
                return ResourceManager.GetString("Filter1EventFoundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen hendelser funnet.
        /// </summary>
        internal static string FilterNoEventsFoundLabel {
            get {
                return ResourceManager.GetString("FilterNoEventsFoundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hendelser funnet.
        /// </summary>
        internal static string FilterXEventsFoundLabel {
            get {
                return ResourceManager.GetString("FilterXEventsFoundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ugyldig brukernavn/passord, vennligst prøv igjen.
        /// </summary>
        internal static string InvalidLoginLabel {
            get {
                return ResourceManager.GetString("InvalidLoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logg inn.
        /// </summary>
        internal static string LogInButton {
            get {
                return ResourceManager.GetString("LogInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logg inn.
        /// </summary>
        internal static string LoginWindowName {
            get {
                return ResourceManager.GetString("LoginWindowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logg ut.
        /// </summary>
        internal static string LogOutButton {
            get {
                return ResourceManager.GetString("LogOutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mange år til.
        /// </summary>
        internal static string ManyYearsAway {
            get {
                return ResourceManager.GetString("ManyYearsAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skal ikke.
        /// </summary>
        internal static string NotAttendingButton {
            get {
                return ResourceManager.GetString("NotAttendingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Èn dag til.
        /// </summary>
        internal static string OneDayAway {
            get {
                return ResourceManager.GetString("OneDayAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En time til.
        /// </summary>
        internal static string OneHourAway {
            get {
                return ResourceManager.GetString("OneHourAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ett minutt til.
        /// </summary>
        internal static string OneMinuteAway {
            get {
                return ResourceManager.GetString("OneMinuteAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pågår.
        /// </summary>
        internal static string Ongoing {
            get {
                return ResourceManager.GetString("Ongoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over én måned til.
        /// </summary>
        internal static string OverAMonthAway {
            get {
                return ResourceManager.GetString("OverAMonthAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over et år til.
        /// </summary>
        internal static string OverAYearAway {
            get {
                return ResourceManager.GetString("OverAYearAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over.
        /// </summary>
        internal static string OverX {
            get {
                return ResourceManager.GetString("OverX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passord.
        /// </summary>
        internal static string PasswordInputLabel {
            get {
                return ResourceManager.GetString("PasswordInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se emnesiden for rom.
        /// </summary>
        internal static string RoomInfoOnITL {
            get {
                return ResourceManager.GetString("RoomInfoOnITL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innlevering.
        /// </summary>
        internal static string SearchAssignmentLabel {
            get {
                return ResourceManager.GetString("SearchAssignmentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eksamen.
        /// </summary>
        internal static string SearchExamLabelLabel {
            get {
                return ResourceManager.GetString("SearchExamLabelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Søk.
        /// </summary>
        internal static string SearchLabel {
            get {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forelesning.
        /// </summary>
        internal static string SearchLectureLabel {
            get {
                return ResourceManager.GetString("SearchLectureLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vis ledige rom.
        /// </summary>
        internal static string ShowAvailibleRoomsButton {
            get {
                return ResourceManager.GetString("ShowAvailibleRoomsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To uker til.
        /// </summary>
        internal static string ToWeeksAway {
            get {
                return ResourceManager.GetString("ToWeeksAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brukernavn.
        /// </summary>
        internal static string UsernameInputLabel {
            get {
                return ResourceManager.GetString("UsernameInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uke.
        /// </summary>
        internal static string WeekLabel {
            get {
                return ResourceManager.GetString("WeekLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dager til.
        /// </summary>
        internal static string XDaysAway {
            get {
                return ResourceManager.GetString("XDaysAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skulle.
        /// </summary>
        internal static string XDidAttendLabel {
            get {
                return ResourceManager.GetString("XDidAttendLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to timer til.
        /// </summary>
        internal static string XHoursAway {
            get {
                return ResourceManager.GetString("XHoursAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skal.
        /// </summary>
        internal static string XIsAttendingLabel {
            get {
                return ResourceManager.GetString("XIsAttendingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutter til.
        /// </summary>
        internal static string XMinutesAway {
            get {
                return ResourceManager.GetString("XMinutesAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to måneder til.
        /// </summary>
        internal static string XMonthsAway {
            get {
                return ResourceManager.GetString("XMonthsAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to andre.
        /// </summary>
        internal static string XOthers {
            get {
                return ResourceManager.GetString("XOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sekunder igjen:.
        /// </summary>
        internal static string XSecondsAway {
            get {
                return ResourceManager.GetString("XSecondsAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uker til.
        /// </summary>
        internal static string XWeeksAway {
            get {
                return ResourceManager.GetString("XWeeksAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skal.
        /// </summary>
        internal static string YouAreAttendingLabel {
            get {
                return ResourceManager.GetString("YouAreAttendingLabel", resourceCulture);
            }
        }
    }
}
